name: Java CI with Maven

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
    name: Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: ${{ matrix.java }}
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-   
    - name: Build Stable Widgets
      run: xvfb-run mvn -V clean verify  -Dtycho.localArtifacts=ignore
    - name: Build Incubation Widgets
      run: xvfb-run mvn -V clean verify -Pincubation  -Dtycho.localArtifacts=ignore
#    - name: Publish Unit Test Results
#      uses: EnricoMi/publish-unit-test-result-action@v1
#      if: always()
#      with:
#       files: /**/surefire-reports/*.xml
